-- Image Slot Lineage V1 minimal pre-migration schema harness.
--
-- This is intentionally not a complete Payload schema. It contains only the
-- two target tables, representative legacy columns, and deterministic
-- synthetic rows needed to prove additive PostgreSQL compatibility.

BEGIN;

CREATE TABLE public.image_generation_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_ref varchar NOT NULL,
  status varchar NOT NULL,
  provider varchar,
  legacy_result jsonb,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE public.media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename varchar NOT NULL,
  alt varchar,
  mime_type varchar NOT NULL,
  filesize integer,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

INSERT INTO public.image_generation_jobs
  (id, product_ref, status, provider, legacy_result, created_at, updated_at)
VALUES
  (101, 'synthetic-product-a', 'completed', 'fixture', '{"images": 5, "fixture": true}'::jsonb, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z'),
  (102, 'synthetic-product-b', 'pending', NULL, NULL, '2026-01-02T00:00:00Z', '2026-01-02T00:00:00Z');

INSERT INTO public.media
  (id, filename, alt, mime_type, filesize, created_at, updated_at)
VALUES
  (201, 'synthetic-a.webp', 'Synthetic fixture A', 'image/webp', 12345, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z'),
  (202, 'synthetic-b.webp', NULL, 'image/webp', 23456, '2026-01-02T00:00:00Z', '2026-01-02T00:00:00Z');

COMMIT;
