/**
 * reverseImageSearch.ts — D-220, extended in D-221, rewritten as orchestrator in D-222
 *
 * Thin orchestrator over the provider modules in `./providers/`.
 *
 * Flow:
 *   1. Ask `providers/index.ts` which provider is active based on env
 *      (REVERSE_SEARCH_PROVIDER + credential presence). If none → return
 *      `available: false, externalSearchRan: false` — callers treat this
 *      as a capability gap (matchType `visual_only_no_external_search`).
 *   2. Build the search queue: cap at `provider.maxImages` (2 per D-222
 *      spec). Primary = first original image. Secondary = best supporting
 *      image (already sorted original → enhanced → generated by
 *      `collectImages.ts`). Generated images never override the original's
 *      identity anchor — they only run if supporting[0] is the best we
 *      have, and non-primary/non-original hits are downgraded.
 *   3. Run all per-image searches in PARALLEL (Promise.all) so DataForSEO's
 *      async polling for two images fits in a single Vercel invocation.
 *   4. Merge results by URL (dedupe, keep highest similarity), apply the
 *      source-type downgrade (originals > enhanced > generated), sort.
 *   5. Emit the provider metadata fields so the Telegram report can show
 *      Provider / Queue / Depth / pending-task warnings.
 *
 * Preserved rule from D-220: ordering-based similarity is capped at 85
 * inside the providers, so the provider alone can never promote a result
 * past `similar_style`. The orchestrator in
 * `createProductIntelligenceReport.ts` layers brand-signal heuristics on
 * top to decide the final matchType.
 */

import type {
  PiCollectedImages,
  PiReferenceProduct,
  PiReverseSearchResult,
} from './types'
import { classifyBySimilarity } from './providers/classify'
import { providerAvailability, selectProvider } from './providers'
import type { ProviderSearchResult } from './providers/types'

/** Source-type downgrade (points subtracted from ordering similarity). */
function downgradeFor(
  source: 'original' | 'generated' | 'enhanced',
  isPrimary: boolean,
): number {
  if (isPrimary && source === 'original') return 0
  if (source === 'original') return 5 // non-primary original (extra angle)
  if (source === 'enhanced') return 10 // retouched original
  return 15 // fully generated — weakest identity anchor
}

function applyDowngrade(results: PiReferenceProduct[], points: number): PiReferenceProduct[] {
  if (points <= 0) return results
  return results.map((r) => {
    const downSim = r.similarity != null ? Math.max(50, r.similarity - points) : null
    return {
      ...r,
      similarity: downSim,
      classification: classifyBySimilarity(downSim),
    }
  })
}

/** Merge per-image batches into a single deduped, ranked list. */
function mergeAndRank(batches: PiReferenceProduct[][]): PiReferenceProduct[] {
  const bestByUrl = new Map<string, PiReferenceProduct>()
  for (const batch of batches) {
    for (const r of batch) {
      if (!r.url) continue
      const existing = bestByUrl.get(r.url)
      const newSim = r.similarity ?? -1
      if (!existing) {
        bestByUrl.set(r.url, r)
        continue
      }
      const curSim = existing.similarity ?? -1
      if (newSim > curSim) bestByUrl.set(r.url, r)
    }
  }
  return Array.from(bestByUrl.values()).sort((a, b) => {
    const sa = a.similarity ?? 0
    const sb = b.similarity ?? 0
    if (sb !== sa) return sb - sa
    const qa = (a.price ? 1 : 0) + (a.snippet ? 1 : 0)
    const qb = (b.price ? 1 : 0) + (b.snippet ? 1 : 0)
    return qb - qa
  })
}

interface QueueItem {
  url: string
  source: 'original' | 'generated' | 'enhanced'
  isPrimary: boolean
}

function buildSearchQueue(images: PiCollectedImages, cap: number): QueueItem[] {
  const queue: QueueItem[] = []
  if (images.primary) {
    queue.push({
      url: images.primary.url,
      source: images.primary.source,
      isPrimary: true,
    })
  }
  for (const s of images.supporting) {
    if (queue.length >= cap) break
    queue.push({ url: s.url, source: s.source, isPrimary: false })
  }
  return queue
}

/**
 * Run a reverse image search over the collected images using the selected
 * provider. Returns `available: false` when no provider is configured.
 */
export async function runReverseImageSearch(
  images: PiCollectedImages,
): Promise<PiReverseSearchResult> {
  const provider = selectProvider()
  const avail = providerAvailability()

  if (!provider) {
    return {
      available: false,
      provider: null,
      results: [],
      raw: {
        note: 'no_reverse_search_provider_configured',
        availability: avail,
      },
      externalSearchRan: false,
      searchedImageCount: 0,
      onlineMatchesFound: 0,
      searchedImageSources: [],
      providerDisplayName: null,
      providerQueue: null,
      providerDepth: null,
      pendingTaskIds: [],
    }
  }

  const queue = buildSearchQueue(images, provider.maxImages)

  if (queue.length === 0) {
    return {
      available: true,
      provider: provider.name,
      results: [],
      raw: { note: 'no_images_to_search', provider: provider.name },
      externalSearchRan: false,
      searchedImageCount: 0,
      onlineMatchesFound: 0,
      searchedImageSources: [],
      providerDisplayName: provider.displayName,
      providerQueue: provider.queue ?? null,
      providerDepth: provider.depth ?? null,
      pendingTaskIds: [],
      error: 'no_images_to_search',
    }
  }

  // Run all provider.search calls in parallel. DataForSEO's async polling
  // is the slow path — parallelizing keeps total wall time ~ one image's
  // poll budget instead of two.
  const perImage: ProviderSearchResult[] = await Promise.all(
    queue.map((q) => provider.search(q.url)),
  )

  const batches: PiReferenceProduct[][] = []
  const errors: string[] = []
  const pendingTaskIds: string[] = []
  const contributed: Array<{ url: string; source: 'original' | 'generated' | 'enhanced' }> = []

  perImage.forEach((res, idx) => {
    const q = queue[idx]
    if (res.pending && res.taskId) pendingTaskIds.push(res.taskId)
    if (res.ok) {
      const downgraded = applyDowngrade(res.results, downgradeFor(q.source, q.isPrimary))
      if (downgraded.length > 0) {
        batches.push(downgraded)
        contributed.push({ url: q.url, source: q.source })
      }
    } else if (res.error) {
      errors.push(res.error)
    }
  })

  const merged = mergeAndRank(batches).slice(0, 8)
  const searchedImageCount = queue.length
  const onlineMatchesFound = merged.length

  return {
    available: true,
    provider: provider.name,
    results: merged,
    raw: {
      provider: provider.name,
      providerDisplayName: provider.displayName,
      queue: provider.queue,
      depth: provider.depth,
      searchedImageCount,
      onlineMatchesFound,
      pendingTaskIds,
      perImage: perImage.map((r, idx) => ({
        imageUrl: queue[idx].url,
        source: queue[idx].source,
        isPrimary: queue[idx].isPrimary,
        ok: r.ok,
        pending: r.pending ?? false,
        taskId: r.taskId ?? null,
        resultCount: r.results?.length ?? 0,
        raw: r.raw,
        error: r.error ?? null,
      })),
    },
    externalSearchRan: true,
    searchedImageCount,
    onlineMatchesFound,
    searchedImageSources: contributed,
    providerDisplayName: provider.displayName,
    providerQueue: provider.queue ?? null,
    providerDepth: provider.depth ?? null,
    pendingTaskIds,
    error: merged.length === 0 && errors.length > 0 ? errors[0] : undefined,
  }
}

// Re-export for any legacy caller that imported this from reverseImageSearch.
export { classifyBySimilarity }
