import assert from 'node:assert'
import { existsSync, readFileSync, readdirSync } from 'node:fs'

const manifestPath = 'project-control/LOCAL_RELEASE_CANDIDATE.md'

function read(path: string): string {
  return readFileSync(path, 'utf8')
}

function assertIncludes(haystack: string, needle: string, label: string): void {
  assert.ok(haystack.includes(needle), `${label} must include: ${needle}`)
}

assert.ok(existsSync(manifestPath), 'local release candidate manifest is missing')

const manifest = read(manifestPath)
const packageJson = JSON.parse(read('package.json')) as {
  scripts?: Record<string, string>
}
const agents = read('AGENTS.md')
const claude = read('CLAUDE.md')
const opsSourcePack = read('chatgpt-project-sources/13_VALIDATION_DEPLOYMENT_OPS.md')
const nextSprint = read('chatgpt-project-sources/17_OPEN_QUESTIONS_AND_NEXT_SPRINT.md')
const mdFiles = readdirSync('chatgpt-project-sources').filter((name) => name.endsWith('.md'))

for (const phrase of [
  'D-397/D-500 Local release candidate boundary',
  'D-398 local PR review package',
  'D-399 loading-plan first product worklist',
  'D-400 Shopier dashboard batch review sample',
  'D-401 OpenClaw VPS verification guardrail',
  'D-402 historical soak-script quarantine',
  'D-403 provider reality audit',
  'D-404 image regeneration plan',
  'D-405 image-plan runtime smoke',
  'D-406 Shopier runtime-smoke batch review alignment',
  'D-422 product-flow operator checklist',
  'D-423 product-flow checklist dependency ordering',
  'D-424 product-flow primary operator step',
  'D-425 load-plan product-flow handoff',
  'D-426 operator smoke-plan load-plan handoff alignment',
  'D-427 load-plan runtime product-flow handoff',
  'D-428 Shopier dashboard product-flow handoff',
  'D-429 Shopier preview product-flow handoff',
  'D-430 operator smoke-plan Shopier handoff alignment',
  'D-431 operator smoke-plan Shopier credential hold',
  'D-432 operator smoke-plan manual ad preflight alignment',
  'D-433 operator smoke-plan storefront trust preflight',
  'D-434 operator smoke-plan inquiry guard preflight',
  'D-435 operator smoke-plan attribution preflight',
  'D-436 operator smoke-plan sitemap preflight',
  'D-437 operator smoke-plan Telegram access preflight',
  'D-438 Product Flow Snapshot operator links',
  'D-439 loading-plan worklist operator links',
  'D-440 Shopier preview/dashboard operator links',
  'D-441 Shopier preview credential holds',
  'D-442 lead follow-up operator links',
  'D-443 operator inbox product links',
  'D-444 lead desk operator links',
  'D-445 order desk operator links',
  'D-446 business snapshot next-action hints',
  'D-447 funnel snapshot next-action hints',
  'D-448 ad-readiness next-action hints',
  'D-449 operator smoke-plan latest-boundary label',
  'D-450 retired-channel memory-lock guardrail',
  'D-451 PDP conversion trust guardrail',
  'D-452 ad-readiness storefront trust hint',
  'D-453 source-pack latest-boundary guardrail',
  'D-454 loading-plan batch summary',
  'D-455 loading-plan batch focus',
  'D-456 loading-plan focus queue',
  'D-457 loading-plan focus details',
  'D-458 product-flow checklist summary',
  'D-459 product-flow dispatch summary',
  'D-460 product-flow dispatch recovery paths',
  'D-461 control-truth Memory Lock reconciliation',
  'D-462 BlogPosts featured-image schema drift repair',
  'D-463 Mentix skill runtime-truth reconciliation',
  'D-464 homepage merchandising rail wiring',
  'D-465 Obsidian control-center alignment',
  'D-466 protected-brand remediation plan',
  'D-467 protected-brand manual activation hard gate',
  'D-468 product workflow golden path',
  'D-469 Turbopack workspace-root pin',
  'D-470 Product Flow action-ID handoff',
  'D-471 public storefront safety gate',
  'D-472 verified storefront metrics gate',
  'D-473 Product Flow Website visibility truth',
  'D-474 safe public PDP link policy',
  'D-475 direct Telegram UTM guard',
  'D-476 catalog risk-first loading-plan order',
  'D-477 protected-brand provenance review audit',
  'D-478 provenance review delivery idempotency',
  'D-479 Blog editorial preflight and first-publication guard',
  'D-480 Shopier webhook authenticity fail-closed guard',
  'D-481 Shopier order-ID duplicate-safety guard and applied, post-apply-verified index',
  'D-482 Shopier order and stock transaction boundary',
  'D-483 non-Shopier order stock transaction boundary',
  'D-484 non-Shopier conditional stock reservation',
  'D-485 Shopier atomic floor-at-zero decrement',
  'D-486 storefront image fallback and structured data safety',
  'D-487 shared Blog and PDP JSON-LD serialization',
  'D-488 optional OpenClaw VPS deploy guard',
  'D-489 confirmation-wizard schema governance',
  'D-490 lead-status enum schema governance',
  'D-491 order-to-lead relationship schema governance',
  'D-492 storefront header and Camper brand-safety correction',
  'D-493 X direct/fallback provider readiness alignment',
  'D-494 Meta gallery media selection alignment',
  'D-495 Meta public-media dispatch preflight',
  'D-496 lead-followup runtime smoke completeness',
  'D-497 brand remediation external-exposure visibility',
  'D-498 brand remediation provenance-state workflow',
  'D-499 batch Image QC remediation queue',
  'D-500 Meta provider configuration unification',
  'Status: D-380-D-500 merged to `main` via PR #6, with D-501 merged via PR #7',
  'the D-501 deployment also completed successfully.',
  'Payload/Next remains the source of truth',
  'Active channels are Website, Instagram, Facebook, X, and Shopier.',
  'Dolap and Threads are retired.',
  'SupplierScout is dormant.',
  'n8n is optional glue only.',
  'Shopier remains the checkout/sales bridge',
  'npm run validate',
  'npm run test:local-pr-review',
  'npm run test:loading-plan',
  'npm run test:brand-provenance-review',
  'npm run test:brand-provenance-command',
  'npm run test:blog-preflight',
  'npm run test:blog-publishing-guard',
  'npm run test:blog-preflight-command',
  'npm run test:shopier-webhook-security',
  'npm run test:shopier-webhook-local',
  'npm run test:order-stock-transaction',
  'npm run test:shopier-publish-control',
  'npm run test:lead-followup-plan',
  'npm run test:lead-desk',
  'npm run test:order-desk',
  'npm run test:business-desk',
  'npm run test:funnel-desk',
  'npm run test:ad-readiness',
  'npm run test:utm-builder',
  'npm run test:utm-command',
  'npm run test:operator-inbox',
  'npm run test:shopier-commands',
  'npm run test:openclaw-vps-verification',
  'npm run test:mentix-skills',
  'npm run test:soak-scripts',
  'npm run test:provider-reality',
  'npm run test:image-regeneration-plan',
  'npm run test:runtime-smokes',
  'npm run test:product-flow-snapshot',
  'npm run test:product-workflow',
  'npm run test:product-storefront-images',
  'npm run test:product-structured-data',
  'npm run test:structured-data',
  'npm run test:blog-structured-data',
  'npm run test:inquiry-guard',
  'npm run test:attribution',
  'npm run test:sitemap-entries',
  'npm run test:telegram-access',
  'npm run test:merchandising',
  'npm run test:homepage-merchandising',
  'npm run test:obsidian-control',
  'npm run test:story-dispatch',
  'lint 0 errors / 0 warnings',
  `chatgpt-project-sources contains ${mdFiles.length} Markdown documents`,
  'Vercel Production deployment `dpl_5L6CXiNjKBiqS8sp7DAuRabcG1cj` is Ready',
  'No live Telegram command, optional OpenClaw sync, live Shopier webhook smoke, provider call, external dispatch, queue write, ad spend, SupplierScout activation, or retired-channel activation has been performed',
  'The approved PR review merged PR #6 into `main`.',
  'Do not run live integration smokes unless the operator asks.',
]) {
  assertIncludes(manifest, phrase, 'local release candidate manifest')
}

for (const checkpoint of [
  'D-380',
  'D-381',
  'D-382',
  'D-383',
  'D-384',
  'D-385',
  'D-386',
  'D-387',
  'D-388',
  'D-389',
  'D-390',
  'D-391',
  'D-392',
  'D-393',
  'D-394',
  'D-395',
  'D-396',
  'D-397',
  'D-398',
  'D-399',
  'D-400',
  'D-401',
  'D-402',
  'D-403',
  'D-404',
  'D-405',
  'D-406',
  'D-422',
  'D-423',
  'D-424',
  'D-425',
  'D-426',
  'D-427',
  'D-428',
  'D-429',
  'D-430',
  'D-431',
  'D-432',
  'D-433',
  'D-434',
  'D-435',
  'D-436',
  'D-437',
  'D-438',
  'D-439',
  'D-440',
  'D-441',
  'D-442',
  'D-443',
  'D-444',
  'D-445',
  'D-446',
  'D-447',
  'D-448',
  'D-449',
  'D-450',
  'D-451',
  'D-452',
  'D-453',
  'D-454',
  'D-455',
  'D-456',
  'D-457',
  'D-458',
  'D-459',
  'D-460',
  'D-461',
  'D-462',
  'D-463',
  'D-464',
  'D-465',
  'D-466',
  'D-467',
  'D-468',
  'D-469',
  'D-470',
  'D-471',
  'D-472',
  'D-473',
  'D-474',
  'D-475',
  'D-476',
  'D-477',
  'D-478',
  'D-479',
  'D-480',
  'D-481',
  'D-482',
  'D-483',
  'D-484',
  'D-485',
  'D-486',
  'D-487',
  'D-488',
  'D-489',
  'D-490',
  'D-491',
  'D-492',
  'D-493',
  'D-494',
  'D-495',
  'D-496',
  'D-497',
  'D-498',
  'D-499',
  'D-500',
]) {
  assertIncludes(manifest, checkpoint, 'local release candidate checkpoint list')
}

assert.ok(mdFiles.length <= 20, `source pack must stay under 21 docs; found ${mdFiles.length}`)

assertIncludes(
  packageJson.scripts?.['test:local-release-candidate'] ?? '',
  'tsx scripts/local-release-candidate-governance.ts',
  'package test:local-release-candidate script',
)
assertIncludes(
  packageJson.scripts?.['test:safe'] ?? '',
  'npm run test:local-release-candidate',
  'safe test suite',
)

for (const doc of [agents, claude]) {
  assertIncludes(doc, 'D-397 local release candidate boundary is local-only', 'agent guidance')
  assertIncludes(doc, 'test:local-release-candidate', 'agent guidance validation list')
}

assertIncludes(opsSourcePack, 'test:local-release-candidate', 'source-pack ops validation')
assertIncludes(opsSourcePack, 'project-control/LOCAL_RELEASE_CANDIDATE.md', 'source-pack release manifest pointer')
assertIncludes(nextSprint, 'D-397 local release candidate boundary added and governance-tested locally.', 'next sprint release boundary')

console.log('localReleaseCandidateGovernance: local release boundary, source-pack count, and handoff guardrails - ALL OK')
